ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

admin.site.site_header = "Look & Take Administration"
admin.site.site_title = "Look & Take"
admin.site.index_title = "Welcome to Look & Take Portal"

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('', include('product.urls')),
                  path('', include('inventory.urls')),
                  path('', include('order.urls')),
                  # path('cart/', TemplateView.as_view(template_name='cart.html'), name='cart'),
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('vendor/', views.VendorListView.as_view(), name='vendor_list'),
    path('add_vendor/', views.VendorCreateView.as_view(), name='vendor_create'),
    path('stock/', views.StockListView.as_view(), name='stock_list'),
    path('add_stock/', views.StockCreateView.as_view(), name='stock_create'),
    # path('create/', views.create_session),
    # path('get/', views.get_session),
    # path('delete/', views.delete_session),
    # path('createcookie/', views.cookie_session),
    # path('deletecookie/', views.cookie_delete),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('order/', views.OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('add_order/', views.OrderCreateView.as_view(), name='order_create'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('brand/', views.BrandListView.as_view(), name='brand_list'),
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('add_product/', views.ProductCreateView.as_view(), name='product_create'),
    path('add_brand/', views.BrandCreateView.as_view(), name='brand_create'),
    path('add_category/', views.CategoryCreateView.as_view(), name='category_create'),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/check_out/', views.check_out, name='check_out'),
    path('cart/', views.CartView.as_view(), name='cart_view'),
    path('accounts/signup', views.SignUpView.as_view(), name='signup'),
]

product/models.py
from django.db import models
from django.core.exceptions import ValidationError

CHOICE = (
        ('Available', 'Available'),         # ('Actual Value', 'Human Readable Name')
        ('Not Available', 'Not Available')      # ('Actual Value', 'Human Readable Name')
    )


def validate_negative_value(value):  # creating a validator function for negative values
    if value <= 0:
        raise ValidationError('Enter positive value')
    else:
        return value


class Brand(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=50, choices=CHOICE, default='Not Available')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=50, choices=CHOICE, default='Not Available')

    def __str__(self):
        return self.name


class Products(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='brand')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200, null=True)
    code = models.CharField(max_length=100)
    quantity = models.IntegerField(default=0, blank=True, validators=[validate_negative_value])
    price = models.PositiveIntegerField()
    count_sold = models.PositiveIntegerField(default=0, blank=True)
    status = models.CharField(max_length=50, choices=CHOICE, default='Not Available')
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.name

templates/cart.html
{% extends "home.html" %}
{% block content %}
    <h1 class="text-center text-warning bg-light">SHOPPING CART</h1>
    {% if request.session.cart.items %}
        <div class="container">
            <table class="table table-borderless">
                {% if request.session.cart.items %}
                    {% for key,value in request.session.cart.items %}
                        <tr style="border-width: 0 0 1px 0; line-height: 100px">
                            {#                    <td>{{ forloop.counter }}</td>#}
                            <td><img src="{{ value.image }}" height="100px"></td>
                            <td>{{ value.name }}</td>
                            {#                        <td>{{ value.price }}</td>#}
                            <td><a href="{% url 'product:item_decrement' value.product_id %}"><i
                                    class="fa-solid fa-circle-minus text-warning"></i></a>
                                {{ value.quantity }}
                                <a href="{% url 'product:item_increment' value.product_id %}"><i
                                        class="fa-solid fa-circle-plus text-warning"></i></a></td>
                            <td>Rs. {% widthratio value.price 1 value.quantity %}</td>
                            <td><a class=" btn text-danger text-decoration-none"
                                   href="{% url 'product:item_clear' value.product_id %}">Delete Item</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                    <p class="text-center" style="font-size: 50px">Total Bill: {{ cart_total.total_price }} /-</p>
                    <a class=" btn btn-outline-secondary fs-6"
                       href="{% url 'product:product_list' %}">Continue Shopping</a>
                    <a class=" btn btn-outline-warning" style="margin-left: 23rem"
                       href="{% url 'product:cart_clear' %}">Clear Cart</a>
                    {% if user.is_authenticated %}
                        <a class=" btn btn-outline-success ms-2"
                           href="{% url 'product:check_out' %}">Check Out</a>
                    {% else %}
                        <button class=" btn btn-outline-success ms-2"
                                data-bs-toggle="modal"
                                data-bs-target="#exampleModal"
                        >Check Out
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <strong>Please login to CHECK OUT!</strong>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">
                                            Close
                                        </button>
                                        <a href="{% url 'login' %}" class="btn btn-outline-warning">Login</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
        </div>
    {% else %}
        <p class="text-center pt-4">No items in cart <a class="text-warning text-decoration-none mx-1"
                                                        href="{% url 'product:product_list' %}">Add Items</a></p>
    {% endif %}
{% endblock content %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Look & Take</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .up, .down {
            opacity: 0.4;
            font-size: 0.7rem;
        }

        .up:hover {
            opacity: 1;
            cursor: pointer;
        }

        .down:hover {
            opacity: 1;
            cursor: pointer;
        }

        .main {
            margin-top: 56px; /* Same as the width of the sidenav */
        {#font-size: 20px; /* Increased text to enable scrolling */#}{#padding: 10px 10px;#}
        }
    </style>
    {% block head %}
    {% endblock head %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-warning fixed-top">
    <div class="container-fluid" style="width: 100%">
        <a class="navbar-brand" href="#">Look & Take</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link active" aria-current="page" href="{% url 'product:brand_list' %}">Brand</a>#}
                {#                </li>#}
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link active" href="{% url 'product:category_list' %}">Category</a>#}
                {#                </li>#}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Products
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'product:brand_list' %}">Brands</a></li>
                        <li><a class="dropdown-item" href="{% url 'product:category_list' %}">Category</a></li>
                        <li><a class="dropdown-item" href="{% url 'product:product_list' %}">Products</a></li>
                        {% if user.is_staff %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'product:brand_create' %}">Add Brand</a></li>
                            <li><a class="dropdown-item" href="{% url 'product:category_create' %}">Add Category</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'product:product_create' %}">Add Product</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Inventory
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'inventory:vendor_list' %}">Vendor</a></li>
                            <li><a class="dropdown-item" href="{% url 'inventory:stock_list' %}">Stock</a></li>
                            {% if user.is_staff %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'inventory:vendor_create' %}">Add Vendor</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'inventory:stock_create' %}">Add Stock</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'order:order_list' %}">Orders List</a>
                </li>
                {% if user.is_staff %}
                {% else %}
                    <li id="cart" class="nav-item">
                        <a class="nav-link active position-relative" href="{% url 'product:cart_view' %}">
                            <i class="fa-solid fa-cart-shopping"></i> Cart
                            {% if request.session.cart.items %}
                                <span
                                        class="position-absolute top-1 start-100 translate-middle badge rounded-pill bg-danger">
                            {{ request.session.cart.items|length }}<span
                                        class="visually-hidden">unread messages</span></span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle active mx-2" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-user"></i>
                        {% if user.is_authenticated %}
                            {{ user }}
                        {% else %}
                            My Account
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'product:signup' %}">Signup</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex" method="GET">
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="main">
    {% block content %}
    {% endblock content %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>

templates/look&take.html
{% extends "home.html" %}
{% block content %}


    {% if products_list %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <h1 class="text-center my-4">All Products</h1>
                    <div class="card shadow my-2" style="height: 82.7vh">
                        <div class="card-body">
                            <table class="table table-striped text-center">
                                <thead>
                                <tr>
                                    <th scope="col">Sr. No.</th>
                                    <th scope="col">Product Image</th>
                                    <th scope="col">Product Name <a href="?order_by=name&direction=asc"><i
                                            class="fa-solid fa-arrow-up up"></i></a><a
                                            href="?order_by=name&direction=desc"><i
                                            class="fa-solid fa-arrow-down down"></i></a></th>
                                    <th scope="col">Brand <a href="?order_by=brand&direction=asc"><i
                                            class="fa-solid fa-arrow-up up"></i></a><a
                                            href="?order_by=brand&direction=desc"><i
                                            class="fa-solid fa-arrow-down down"></i></a></th>
                                    <th scope="col">Category <a href="?order_by=category&direction=asc"><i
                                            class="fa-solid fa-arrow-up up"></i></a><a
                                            href="?order_by=category&direction=desc"><i
                                            class="fa-solid fa-arrow-down down"></i></a></th>
                                    <th scope="col">Product Code <a href="?order_by=code&direction=asc"><i
                                            class="fa-solid fa-arrow-up up"></i></a><a
                                            href="?order_by=code&direction=desc"><i
                                            class="fa-solid fa-arrow-down down"></i></a></th>
                                    <th scope="col">Unit Price <a href="?order_by=price&direction=asc"><i
                                            class="fa-solid fa-arrow-up up"></i></a><a
                                            href="?order_by=price&direction=desc"><i
                                            class="fa-solid fa-arrow-down down"></i></a></th>
                                    <th scope="col">Availabe Qty <a href="?order_by=quantity&direction=asc"><i
                                            class="fa-solid fa-arrow-up up"></i></a><a
                                            href="?order_by=quantity&direction=desc"><i
                                            class="fa-solid fa-arrow-down down"></i></a></th>
                                    <th scope="col">Shop <i class="fa-solid fa-cart-shopping"></i></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for product in products_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td><img height="35px" src="{{ product.image.url }}"></td>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.brand }}</td>
                                        <td>{{ product.category }}</td>
                                        <td>{{ product.code }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>
                                        {% if product.quantity > 1 %}
                                            <td><a class=" btn border-success text-success text-decoration-none"
                                                   href="{% url 'product:cart_add' product.id %}">Add to Cart</a></td>
                                        {% else %}
                                            <td></td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card shadow mt-3" style="height: 90vh">
                        <div class="card-body">
                            <h1 class="card-title text-center">Cart Detail</h1>
                            <table class="table text-center">
                                <thead>
                                <tr>
                                    <th scope="col">Sr.#</th>
                                    <th scope="col">Product Name</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Total Price</th>
                                    <th scope="col"><i class="fa-solid fa-trash-can"></i></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if request.session.cart.items %}
                                    {% for key,value in request.session.cart.items %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ value.name }}</td>
                                            <td>{{ value.price }}</td>
                                            <td><a href="{% url 'product:item_decrement' value.product_id %}"><i
                                                    class="fa-solid fa-minus up"></i></a> {{ value.quantity }} <a
                                                    href="{% url 'product:item_increment' value.product_id %}"><i
                                                    class="fa-solid fa-plus up"></i></a></td>
                                            <td>{% widthratio value.price 1 value.quantity %}</td>
                                            <td><a class=" btn border-danger text-danger text-decoration-none"
                                                   href="{% url 'product:item_clear' value.product_id %}">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                    </table>
                                    <p>Total Bill: {{ cart_total.total_price }} /-</p>
                                    <a class=" btn border-warning text-warning text-decoration-none"
                                       href="{% url 'product:cart_clear' %}">Clear Cart</a>

                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p class="text-center">No Products are available.</p>
    {% endif %}

{% endblock content %}