ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

admin.site.site_header = "Look & Take Administration"
admin.site.site_title = "Look & Take"
admin.site.index_title = "Welcome to Look & Take Portal"

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('', include('product.urls')),
                  path('', include('inventory.urls')),
                  path('', include('order.urls')),
                  # path('cart/', TemplateView.as_view(template_name='cart.html'), name='cart'),
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('order/', views.OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('add_order/', views.OrderCreateView.as_view(), name='order_create'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models

from product.models import Products

CHOICE = (
        ('Approved', 'Approved'),          # ('Actual Value', 'Human Readable Name')
        ('Not Approved', 'Not Approved')       # ('Actual Value', 'Human Readable Name')
    )


class Orders(models.Model):
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=50, choices=CHOICE, default='Not Approved')
    total = models.PositiveIntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-date_created']


class OrderDetails(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product')
    quantity = models.PositiveIntegerField()
    price_each = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField()
    discount_price = models.PositiveIntegerField()
    final_price = models.PositiveIntegerField()

    def __str__(self):
        return str(self.user_id)

order/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Orders, OrderDetails


class OrderListView(generic.ListView):
    model = Orders
    template_name = 'order/orders.html'

    def get_queryset(self):
        super().get_queryset()
        order_by = self.request.GET.get('order_by')
        direction = self.request.GET.get('direction')
        order = Orders.objects.all()
        if direction:
            if direction == 'asc':
                ordering = '{}'.format(order_by)
            else:
                ordering = '-{}'.format(order_by)
            order = order.order_by(ordering)
        return order


class OrderCreateView(generic.CreateView):
    model = Orders
    fields = [
        'name',
    ]

    def get_success_url(self):
        return reverse('order:order_list')


class OrderDetailView(generic.DetailView):
    model = Orders
    template_name = 'order/orderdetails.html'

    def dispatch(self, request, *args, **kwargs):
        obj = get_object_or_404(Orders, pk=self.kwargs['pk'])
        if self.request.user.is_staff:
            return super().dispatch(request, *args, **kwargs)
        else:
            if self.request.user.username == obj.name:
                return super().dispatch(request, *args, **kwargs)
            else:
                raise Http404

templates/order/orderdetails.html
{% extends "home.html" %}
{% block content %}
<div style="margin-top: 90px">
    <h1 class="text-center my-4">Order Details of {{ orders.name }}</h1>

    {% if orders %}
        <div class="container">
            <div class="card bg-transparent border-success my-3">
                <div class="card-body">
                    <table class="table table-striped text-center">
                        <thead>
                        <tr>
                            <th scope="col">Sr. No.</th>
                            <th scope="col">Product Name</th>
                            <th scope="col">Order Quantity</th>
                            <th scope="col">Product Price</th>
                            <th scope="col">Total Price</th>
                            <th scope="col">Discount Price</th>
                            <th scope="col">Final Price</th>
                            <th scope="col">Created By</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ord in object.orderdetails_set.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ ord.product.name }}</td>
                                <td>{{ ord.quantity }}</td>
                                <td>{{ ord.product.price }}</td>
                                <td>{{ ord.total_price }}</td>
                                <td>{{ ord.discount_price }}</td>
                                <td>{{ ord.final_price }}</td>
                                <td>{{ ord.user }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <h6 style="text-align: center">Total Bill: {{ orders.total }}</h6>
                </div>
            </div>
        </div>
    {% else %}
        <p class="text-center">No Orders are available.</p>
    {% endif %}

</div>

{% endblock content %}

templates/order/orders.html
{% extends "home.html" %}
{% block content %}
    <div style="margin-top: 90px">
    <h1 class="text-center my-4">Orders List</h1>

    {% if orders_list %}
        <div class="container">
            <div class="card bg-transparent border-success my-3">
                <div class="card-body">
                    <table class="table table-striped text-center">
                        <thead>
                        <tr>
                            <th scope="col">Order ID</th>
                            <th scope="col">Order By <a href="?order_by=name&direction=asc"><i
                                    class="fa-solid fa-arrow-up up"></i></a><a href="?order_by=name&direction=desc"><i
                                    class="fa-solid fa-arrow-down down"></i></a></th>
                            <th scope="col">Order Status <a href="?order_by=status&direction=asc"><i
                                    class="fa-solid fa-arrow-up up"></i></a><a href="?order_by=status&direction=desc"><i
                                    class="fa-solid fa-arrow-down down"></i></a></th>
                            <th scope="col">Total Price <a href="?order_by=total&direction=asc"><i
                                    class="fa-solid fa-arrow-up up"></i></a><a href="?order_by=total&direction=desc"><i
                                    class="fa-solid fa-arrow-down down"></i></a></th>
                            <th scope="col">Date Created <a href="?order_by=date_created&direction=asc"><i
                                    class="fa-solid fa-arrow-up up"></i></a><a
                                    href="?order_by=date_created&direction=desc"><i
                                    class="fa-solid fa-arrow-down down"></i></a></th>
                            {#                            <th scope="col">Date Modified <a href="?order_by=date_modified&direction=asc"><i#}
                            {#                                    class="fa-solid fa-arrow-up up"></i></a><a href="?order_by=date_modified&direction=desc"><i#}
                            {#                                    class="fa-solid fa-arrow-down down"></i></a></th>#}
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders_list %}
                            {% if user.is_staff %}
                                <tr>
                                    <td>{{ order.id }}</td>
                                    <td><a href="{% url 'order:order_detail' order.id %}">{{ order.name }}</a></td>
                                    <td>{{ order.status }}</td>
                                    <td>{{ order.total }}</td>
                                    <td>{{ order.date_created }}</td>
                                </tr>
                            {% elif user.username == order.name %}
                                <tr>
                                    <td>{{ order.id }}</td>
                                    <td><a href="{% url 'order:order_detail' order.id %}">{{ order.name }}</a></td>
                                    <td>{{ order.status }}</td>
                                    <td>{{ order.total }}</td>
                                    <td>{{ order.date_created }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    {% else %}
        <p class="text-center">No Orders are available.</p>
    {% endif %}
    </div>

{% endblock content %}

templates/order/orders_form.html
{% extends "home.html" %}
{% load crispy_forms_filters %}
{% block content %}


    <h1 class="text-center my-3">Add Order</h1>
<form class="mx-5" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add">
</form>

{% endblock content %}